---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gowebapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gowebapp
    spec:
      containers:
      - name: gowebapp
        image: ragsns/gowebapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gowebapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: gowebapp
